"""Remapping helpers for HEALPix targets.

This module contains the weight-generation and weight-application logic used by
[`regrid_to_healpix`][grid_doctor.remap.regrid_to_healpix].

All remapping is performed via reusable NetCDF weight files generated by
ESMF (in-memory via ESMPy or offline via ``ESMF_RegridWeightGen``) and
applied with SciPy sparse matrices.  Two methods are supported:

- ``"nearest"`` — source-to-destination nearest-neighbour mapping.
- ``"conservative"`` — first-order area-weighted conservative remapping.

The implementation works with regular lon/lat grids, curvilinear lon/lat
grids, and unstructured polygon meshes such as ICON.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, cast

import numpy as np
import xarray as xr

from .remap_apply import (
    apply_weights_nd,
    extract_sparse_weights,
)
from .remap_backend import (
    _UNSTRUCTURED_DIMS,
    OfflineWeightConfig,
    _canonical_lon,
    _get_latlon_arrays,
    _get_spatial_dims,
    _get_unstructured_dim,
    _is_unstructured,
    _normalise_angle_units,
    _require_healpix_geo_module,
    compute_healpix_weights_backend,
)
from .types import (
    ApplyBackend,
    FloatArray,
    MissingPolicy,
    RemapMethod,
    SourceKind,
    SourceUnits,
)

logger = logging.getLogger(__name__)


# ===================================================================
# Source-centre coordinate extraction
# ===================================================================


def _source_centre_arrays(
    ds: xr.Dataset,
    *,
    source_units: SourceUnits,
) -> tuple[FloatArray, FloatArray, tuple[str, ...]]:
    """Extract flattened source-centre coordinates and dimension names.

    Args:
        ds: Source dataset.
        source_units: Angular unit convention.

    Returns:
        ``(lat, lon, source_dims)``.
    """
    lat, lon = _get_latlon_arrays(ds)
    lat = _normalise_angle_units(lat, source_units)
    lon = _canonical_lon(_normalise_angle_units(lon, source_units))

    if _is_unstructured(ds):
        spatial_dim = _get_unstructured_dim(ds)
        return lat.ravel(), lon.ravel(), (spatial_dim,)

    y_dim, x_dim = _get_spatial_dims(ds)
    if lat.ndim == 1:
        lon2d, lat2d = np.meshgrid(lon, lat)
        return lat2d.ravel(), lon2d.ravel(), (y_dim, x_dim)
    return lat.ravel(), lon.ravel(), (y_dim, x_dim)


# ===================================================================
# HEALPix cell centres
# ===================================================================


def _healpix_centres(
    level: int,
    *,
    nest: bool,
) -> tuple[FloatArray, FloatArray]:
    """Return HEALPix cell-centre coordinates in degrees.

    All geometry uses a spherical ellipsoid, consistent with ESMF's
    internal area calculation and with climate model coordinates.

    Args:
        level: HEALPix refinement level.
        nest: Nested ordering when *True*, otherwise ring.

    Returns:
        ``(lat_deg, lon_deg)`` arrays.
    """
    module, kwargs = _require_healpix_geo_module(nest)
    ipix = np.arange(12 * (4**level), dtype=np.int64)
    lon_deg, lat_deg = module.healpix_to_lonlat(ipix, level, **kwargs)
    return (
        np.asarray(lat_deg, dtype=np.float64),
        _canonical_lon(np.asarray(lon_deg, dtype=np.float64)),
    )


# ===================================================================
# Weight-file reading (xarray layer on top of remap_apply)
# ===================================================================


def _read_weight_file(
    weights_path: str | Path,
) -> tuple[Any, int, int, int, str, str | None, tuple[str, ...] | None]:
    """Read a weight file and return matrix plus metadata.

    Returns:
        ``(matrix, n_target, n_source, level, order, method,
        stored_source_dims)``.
    """
    with xr.open_dataset(weights_path) as wds:
        row_name = "row" if "row" in wds else "dst_address"
        col_name = "col" if "col" in wds else "src_address"
        val_name = "S" if "S" in wds else "remap_matrix"

        matrix, n_target, n_source = extract_sparse_weights(
            row=wds[row_name].values,
            col=wds[col_name].values,
            values=wds[val_name].values,
        )
        level = int(wds.attrs.get("grid_doctor_level", -1))
        order = str(wds.attrs.get("grid_doctor_order", "nested"))
        method_raw = wds.attrs.get("grid_doctor_method")
        method = str(method_raw) if method_raw is not None else None
        stored_source_dims = _parse_source_dims_attr(
            wds.attrs.get("grid_doctor_source_dims")
        )
    return matrix, n_target, n_source, level, order, method, stored_source_dims


# ===================================================================
# Weight generation facade
# ===================================================================


def compute_healpix_weights(
    ds: xr.Dataset | str | Path,
    level: int,
    *,
    method: RemapMethod = "nearest",
    nest: bool = True,
    source_units: SourceUnits = "auto",
    weights_path: str | Path | None = None,
    grid: xr.Dataset | None = None,
    source_kind: SourceKind = "auto",
    ignore_unmapped: bool | None = None,
    large_file: bool = True,
    prefer_offline: bool | None = None,
    nproc: int = 1,
    esmf_regrid_weightgen: str = "ESMF_RegridWeightGen",
    keep_intermediates: bool = False,
    workdir: str | Path | None = None,
    spectral_transform_command: list[str] | tuple[str, ...] | None = None,
) -> Path:
    """Generate a reusable NetCDF weight file for HEALPix remapping.

    Parameters
    ----------
    ds:
        Source dataset or a source path.
    level:
        HEALPix refinement level.  ``nside = 2**level``.
    method:
        ``"nearest"`` or ``"conservative"``.
    nest:
        Use nested HEALPix ordering when `True`.
    source_units:
        Unit convention of the source coordinates.
    weights_path:
        Output NetCDF file.  A temporary file is created when omitted.
    grid:
        Optional external geometry dataset.
    source_kind:
        Explicit source representation or ``"auto"``.
    ignore_unmapped:
        Ignore unmapped destination cells.
    large_file:
        Forwarded to the in-memory ESMPy workflow.
    prefer_offline:
        Force or disable the offline ESMF path.
    nproc:
        Number of MPI ranks for the offline path.
    esmf_regrid_weightgen:
        Name or path of the offline ESMF executable.
    keep_intermediates:
        Keep intermediate mesh files.
    workdir:
        Working directory for offline intermediate files.
    spectral_transform_command:
        External command for ``source_kind="spectral"``.

    Returns
    -------
    pathlib.Path
        Path to the generated NetCDF weight file.

    See Also
    --------
    [`apply_weight_file`][grid_doctor.remap.apply_weight_file]:
        Apply a previously generated weight file.
    """
    offline = OfflineWeightConfig(
        enabled=bool(prefer_offline) if prefer_offline is not None else False,
        nproc=nproc,
        esmf_regrid_weightgen=esmf_regrid_weightgen,
        keep_intermediates=keep_intermediates,
        workdir=Path(workdir) if workdir is not None else None,
    )
    return compute_healpix_weights_backend(
        ds,
        level,
        method=method,
        nest=nest,
        source_units=source_units,
        weights_path=weights_path,
        grid=grid,
        source_kind=source_kind,
        ignore_unmapped=ignore_unmapped,
        large_file=large_file,
        offline=offline,
        spectral_transform_command=spectral_transform_command,
    )


# ===================================================================
# Source-dimension resolution for weight application
# ===================================================================


def _flattened_size(
    ds: xr.Dataset,
    source_dims: tuple[str, ...],
) -> int:
    """Return the product of ``source_dims`` sizes in *ds*."""
    missing = [d for d in source_dims if d not in ds.dims]
    if missing:
        raise ValueError(
            f"source_dims {source_dims!r} not in dataset. Missing: {missing!r}."
        )
    size = 1
    for d in source_dims:
        size *= int(ds.sizes[d])
    return size


def _parse_source_dims_attr(value: object) -> tuple[str, ...] | None:
    """Parse stored source-dimension metadata from a weight file."""
    if value is None:
        return None
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            parsed = [p.strip() for p in text.split(",") if p.strip()]
        if isinstance(parsed, str):
            return (parsed,)
        if isinstance(parsed, list) and all(isinstance(i, str) for i in parsed):
            return tuple(parsed)
        return None
    if isinstance(value, (tuple, list)) and all(isinstance(i, str) for i in value):
        return tuple(value)
    return None


def _guess_source_dims_from_size(
    ds: xr.Dataset,
    n_source: int,
) -> tuple[str, ...] | None:
    """Guess source dimensions when geometry is unavailable."""
    matches = [str(d) for d, s in ds.sizes.items() if int(s) == n_source]
    preferred = [d for d in matches if d in _UNSTRUCTURED_DIMS]
    if len(preferred) == 1:
        return (preferred[0],)
    if len(matches) == 1:
        return (matches[0],)
    return None


def _resolve_source_dims_for_weight_application(
    ds: xr.Dataset,
    *,
    n_source: int,
    grid: xr.Dataset | None,
    source_dims: tuple[str, ...] | None,
    source_units: SourceUnits,
    stored_source_dims: tuple[str, ...] | None,
) -> tuple[str, ...]:
    """Resolve source dimensions for weight application."""
    if source_dims is not None:
        flat = _flattened_size(ds, source_dims)
        if flat != n_source:
            raise ValueError(f"source_dims mismatch: expected {n_source}, got {flat}.")
        return source_dims

    if stored_source_dims is not None:
        try:
            flat = _flattened_size(ds, stored_source_dims)
        except ValueError:
            flat = -1
        if flat == n_source:
            return stored_source_dims

    if grid is not None:
        grid_lat, _, grid_dims = _source_centre_arrays(grid, source_units=source_units)
        if grid_lat.size != n_source:
            raise ValueError(
                f"Grid mismatch: expected {n_source}, got {grid_lat.size}."
            )
        flat = _flattened_size(ds, grid_dims)
        if flat != n_source:
            raise ValueError(f"Grid dims mismatch: expected {n_source}, got {flat}.")
        return grid_dims

    try:
        src_lat, _, inferred = _source_centre_arrays(ds, source_units=source_units)
    except ValueError:
        guessed = _guess_source_dims_from_size(ds, n_source)
        if guessed is not None:
            return guessed
        raise ValueError(
            "Could not infer source geometry. Pass source_dims= or grid=."
        ) from None

    if src_lat.size == n_source:
        return inferred

    guessed = _guess_source_dims_from_size(ds, n_source)
    if guessed is not None:
        return guessed

    raise ValueError(
        f"Weight file expects {n_source} source cells, dataset has "
        f"{src_lat.size}. Pass source_dims= or grid=."
    )


# ===================================================================
# Weight-file application
# ===================================================================


def apply_weight_file(
    ds: xr.Dataset,
    weights_path: str | Path,
    *,
    missing_policy: MissingPolicy = "renormalize",
    grid: xr.Dataset | None = None,
    source_dims: tuple[str, ...] | None = None,
    source_units: SourceUnits = "auto",
    backend: ApplyBackend = "auto",
) -> xr.Dataset:
    """Apply a previously generated ESMF weight file to *ds*.

    Uses the batched engine in
    `grid_doctor.remap_apply` which replaces per-slice
    ``vectorize=True`` with a single batched sparse matmul for a
    typical 10–50× speedup.

    Parameters
    ----------
    ds:
        Source dataset to remap.
    weights_path:
        Path to the NetCDF weight file.
    missing_policy:
        Strategy for handling NaN (missing) values in the source
        grid during weight application.

        ``"renormalize"`` (default)
            Source cells that are NaN are excluded from the
            weighted sum and the weights of the remaining valid
            source cells are rescaled so they sum to 1.  A target
            cell receives a valid value as long as **at least one**
            contributing source cell is valid.  This is the right
            choice for most climate fields: for instance, a
            HEALPix cell on a coastline that partly overlaps land
            (NaN) and partly ocean still receives a valid SST from
            the ocean fraction.

        ``"propagate"``
            If **any** contributing source cell is NaN, the target
            cell is set to NaN — no partial averages.  Use this
            when completeness of the source coverage matters more
            than spatial coverage of the output, for example when
            computing area-integrated flux budgets where a partial
            average would bias the integral.  Note that this is
            very aggressive: a single NaN source cell at the edge
            of a target cell's footprint is enough to discard it.
            For conservative remapping where a HEALPix cell can
            overlap dozens of source cells, large portions of the
            output along coastlines, swath edges, and orbit gaps
            will be NaN.
    grid:
        Optional grid dataset with source geometry.
    source_dims:
        Optional explicit source dimensions.
    source_units:
        Unit convention for geometry-based inference.
    backend:
        Application backend (``"auto"``, ``"scipy"``, ``"numba"``).

    Returns
    -------
    xarray.Dataset
        Dataset on the HEALPix target grid with a ``cell`` dimension.

    Examples
    --------
    ```python
    ds_hp = apply_weight_file(ds_icon, "icon_to_healpix_d8.nc")
    ```
    """
    if missing_policy not in {"renormalize", "propagate"}:
        raise ValueError("missing_policy must be 'renormalize' or 'propagate'.")

    matrix, n_target, n_source, level, order, method, stored_sd = _read_weight_file(
        weights_path
    )

    resolved_sd = _resolve_source_dims_for_weight_application(
        ds,
        n_source=n_source,
        grid=grid,
        source_dims=source_dims,
        source_units=source_units,
        stored_source_dims=stored_sd,
    )
    n_src_dims = len(resolved_sd)

    regridded: dict[str, xr.DataArray] = {}
    for name, data in ds.data_vars.items():
        if not set(resolved_sd).issubset(map(str, data.dims)):
            regridded[str(name)] = data
            continue

        regridded[str(name)] = cast(
            xr.DataArray,
            xr.apply_ufunc(
                apply_weights_nd,
                data,
                input_core_dims=[list(resolved_sd)],
                output_core_dims=[["cell"]],
                exclude_dims=set(resolved_sd),
                dask="parallelized",
                kwargs={
                    "matrix": matrix,
                    "n_source_dims": n_src_dims,
                    "missing_policy": missing_policy,
                    "backend": backend,
                },
                output_dtypes=[np.float64],
                dask_gufunc_kwargs={"output_sizes": {"cell": n_target}},
            ),
        )

    result = xr.Dataset(regridded, attrs=ds.attrs.copy())
    if level >= 0:
        result = _attach_healpix_coords(
            result,
            level=level,
            nest=(order == "nested"),
            method=method,
        )
    return result


# ===================================================================
# HEALPix coordinate attachment
# ===================================================================


def _attach_healpix_coords(
    ds_hp: xr.Dataset,
    *,
    level: int,
    nest: bool,
    method: str | None = None,
) -> xr.Dataset:
    """Attach HEALPix cell-centre coordinates, CRS variable, and metadata.

    Adds:

    - ``cell``, ``latitude``, ``longitude`` coordinates.
    - A scalar ``crs`` coordinate variable whose attributes describe the
      HEALPix grid (``grid_mapping_name``, ``healpix_nside``, …).
    - ``grid_mapping = "crs"`` on every data variable so that CF-aware
      tools can discover the projection automatically.
    - Global provenance attributes (``healpix_*``, ``grid_doctor_*``).
    """
    import grid_doctor as _gd

    nside = 2**level
    order = "nested" if nest else "ring"

    lat_deg, lon_deg = _healpix_centres(level, nest=nest)
    ds_hp = ds_hp.assign_coords(
        cell=np.arange(lat_deg.size, dtype=np.int64),
        latitude=("cell", lat_deg),
        longitude=("cell", lon_deg),
        crs=_make_crs_variable(level=level, nside=nside, order=order),
    )

    # Tag every spatially-mapped data variable.
    for name in ds_hp.data_vars:
        if "cell" in ds_hp[name].dims:
            ds_hp[name].attrs["grid_mapping"] = "crs"

    # Global HEALPix metadata.
    ds_hp.attrs["healpix_level"] = level
    ds_hp.attrs["healpix_nside"] = nside
    ds_hp.attrs["healpix_order"] = order

    # Provenance.
    ds_hp.attrs["grid_doctor_version"] = _gd.__version__
    if method is not None:
        ds_hp.attrs["grid_doctor_method"] = method

    return ds_hp


def _make_crs_variable(
    *,
    level: int,
    nside: int,
    order: str,
) -> xr.DataArray:
    """Create a scalar CRS coordinate variable for HEALPix.

    The variable follows the CF ``grid_mapping`` convention: a
    dimensionless scalar whose attributes describe the coordinate
    reference system.

    Args:
        level: HEALPix refinement level.
        nside: ``2**level``.
        order: ``"nested"`` or ``"ring"``.

    Returns:
        Scalar :class:`xarray.DataArray`.
    """
    return xr.DataArray(
        np.float64(0.0),
        attrs={
            "grid_mapping_name": "healpix",
            "healpix_nside": nside,
            "healpix_level": level,
            "healpix_order": order,
        },
    )


# ===================================================================
# High-level remapping entry points
# ===================================================================


def regrid_to_healpix(
    ds: xr.Dataset,
    level: int,
    *,
    nest: bool = True,
    method: RemapMethod = "conservative",
    source_units: SourceUnits = "auto",
    weights_path: str | Path | None = None,
    missing_policy: MissingPolicy = "renormalize",
    backend: ApplyBackend = "auto",
    grid: xr.Dataset | None = None,
    source_kind: SourceKind = "auto",
    ignore_unmapped: bool | None = None,
    large_file: bool = True,
    prefer_offline: bool | None = None,
    nproc: int = 1,
    esmf_regrid_weightgen: str = "ESMF_RegridWeightGen",
    keep_intermediates: bool = False,
    workdir: str | Path | None = None,
    spectral_transform_command: list[str] | tuple[str, ...] | None = None,
) -> xr.Dataset:
    """Regrid *ds* to a HEALPix target grid.

    Parameters
    ----------
    ds:
        Source dataset on a regular, curvilinear, or unstructured grid.
    level:
        HEALPix refinement level.
    nest:
        Use nested HEALPix ordering when ``True``.
    method:
        ``"nearest"`` or ``"conservative"``.
    source_units:
        Coordinate units for the source grid.
    weights_path:
        Optional existing or target weight file.
    missing_policy:
        How NaN values in the source grid are treated.
        ``"renormalize"`` (default) excludes NaN source cells and
        rescales the remaining weights so that a target cell is valid
        whenever at least one source cell contributes — appropriate
        for most continuous fields.  ``"propagate"`` sets a target
        cell to NaN if any contributing source cell is NaN — useful
        for strict budget-closure checks but very aggressive along
        coastlines and data edges.  See
        [`apply_weight_file`][grid_doctor.remap.apply_weight_file]
        for a detailed description.
    backend:
        Application backend (``"auto"``, ``"scipy"``, ``"numba"``).
    grid:
        Optional external geometry dataset.
    source_kind:
        Explicit source representation or ``"auto"``.
    ignore_unmapped:
        Ignore unmapped destination cells.
    large_file:
        Forwarded to the in-memory ESMPy workflow.
    prefer_offline:
        Force or disable the offline ESMF path.
    nproc:
        Number of MPI ranks for the offline path.
    esmf_regrid_weightgen:
        Name or path of the offline ESMF executable.
    keep_intermediates:
        Keep intermediate mesh files.
    workdir:
        Working directory for offline intermediate files.
    spectral_transform_command:
        External command for ``source_kind="spectral"``.

    Returns
    -------
    xarray.Dataset
        Regridded dataset on the HEALPix grid.
    """
    weight_file = Path(weights_path) if weights_path is not None else None
    if weight_file is None or not weight_file.exists():
        weight_file = compute_healpix_weights(
            ds,
            level,
            method=method,
            nest=nest,
            source_units=source_units,
            weights_path=weight_file,
            grid=grid,
            source_kind=source_kind,
            prefer_offline=prefer_offline,
            nproc=nproc,
            esmf_regrid_weightgen=esmf_regrid_weightgen,
            keep_intermediates=keep_intermediates,
            workdir=workdir,
            spectral_transform_command=spectral_transform_command,
            ignore_unmapped=ignore_unmapped,
            large_file=large_file,
        )
    return apply_weight_file(
        ds,
        weight_file,
        missing_policy=missing_policy,
        backend=backend,
    )


def regrid_unstructured_to_healpix(
    ds: xr.Dataset,
    level: int,
    *,
    nest: bool = True,
    method: RemapMethod = "conservative",
    source_units: SourceUnits = "auto",
    weights_path: str | Path | None = None,
    missing_policy: MissingPolicy = "renormalize",
) -> xr.Dataset:
    """Compatibility wrapper around [`regrid_to_healpix`][grid_doctor.remap.regrid_to_healpix]."""
    if not _is_unstructured(ds):
        raise ValueError("Expected an unstructured source grid.")
    return regrid_to_healpix(
        ds,
        level,
        nest=nest,
        method=method,
        source_units=source_units,
        weights_path=weights_path,
        missing_policy=missing_policy,
    )


__all__ = [
    "apply_weight_file",
    "compute_healpix_weights",
    "regrid_to_healpix",
    "regrid_unstructured_to_healpix",
]
