"""Point-binning for swath and other point-sampled data.

This module maps *point-sampled* data — satellite Level-2 swaths, station
records, trajectories, or any dataset where every sample carries its own
latitude/longitude — onto the standard grid-doctor HEALPix representation.

Point data cannot go through the ESMF weight path in
[`grid_doctor.remap`][grid_doctor.remap]:

- every granule (orbit frame) has unique geometry, so weight files can
  never be reused, and
- ESMF's nearest source-to-destination method would assign a value to
  *every* global HEALPix cell, smearing a narrow swath over the whole
  sphere.

Instead, [`bin_to_healpix`][grid_doctor.swath.bin_to_healpix] assigns each
sample to the HEALPix cell containing it and reduces all samples per cell.
In the oversampled limit — source pixel spacing much finer than the target
cell spacing — the per-cell sample **mean** converges to the area-weighted
mean and is therefore the binning analogue of conservative remapping,
while the per-cell **mode** is the analogue of nearest-neighbour remapping
for categorical fields.  Choose the target level accordingly: the HEALPix
cell spacing (``58.6° / 2**level``) should be coarser than the sample
spacing, exactly as
[`resolution_to_healpix_level`][grid_doctor.helpers.resolution_to_healpix_level]
would suggest.

All cell geometry uses a perfect sphere, consistent with the rest of
grid-doctor and with the Waterpark technical decisions.  Geodetic (WGS84)
latitudes are deliberately interpreted as spherical: the maximum
discrepancy (~0.19° at 45° latitude) is accepted so that all datasets in a
hub share one indexing geometry and overlay without systematic offsets.

The output of the dense path carries the full grid-doctor metadata
(``crs`` variable, ``healpix_*`` and ``grid_doctor_*`` attributes) so that
[`coarsen_healpix`][grid_doctor.helpers.coarsen_healpix],
[`save_pyramid`][grid_doctor.helpers.save_pyramid], and CF-aware viewers
work unchanged.

Acknowledgments
---------------
The binning approach — direct cell assignment via ``healpix_geo`` plus
grouped reduction with ``numpy_groupies``, including mode aggregation
through per-class counting — was informed by earlier EarthCARE-to-HEALPix
conversion work by Anne Fouilloux
(https://github.com/annefou/earthcare-dggs, MIT licensed).  This module
is an independent implementation and deliberately diverges on cell
indexing (perfect sphere instead of WGS84, for hub-wide alignment) and
fill-value handling (declared attributes instead of dtype conventions).

The initial implementation of this module, its test suite, and the
accompanying documentation were largely generated by Claude, an AI
assistant made by Anthropic, working from the grid-doctor codebase and
the Waterpark technical-decisions document; the code was reviewed,
adapted, and is maintained by the grid-doctor developers.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping

import numpy as np
import xarray as xr

from ..cf import (
    HealpixNested,
    HealpixRing,
)
from ..remap import _attach_healpix_coords
from ..remap_backend import (
    _canonical_lon,
    _require_healpix_geo_module,
)
from ..types import (
    HEALPIX_INDEX,
    HEALPIX_LEVEL,
    HEALPIX_NSIDE,
    HEALPIX_ORDER,
    BinAgg,
    Int64Array,
    SourceUnits,
)
from .utils import (
    AGG_TO_METHOD,
    FILL_ATTR_NAMES,
    MAX_NESTED_LEVEL,
    NPG_FUNC,
    bin_count,
    bin_mode,
    bin_simple,
    masked_float64,
    resolve_methods,
    resolve_point_coords,
)

logger = logging.getLogger(__name__)

# ===================================================================
# Public API
# ===================================================================


def bin_to_healpix(
    ds: xr.Dataset,
    level: int,
    *,
    agg: BinAgg | Mapping[str, BinAgg] = "mean",
    nest: bool = True,
    lat_name: str | None = None,
    lon_name: str | None = None,
    source_units: SourceUnits = "auto",
    fill_values: Mapping[str, float] | None = None,
    min_count: int = 1,
    with_counts: bool = False,
    dense: bool = True,
) -> xr.Dataset:
    """Bin point-sampled data into HEALPix cells.

    Every sample is assigned to the HEALPix cell containing its
    coordinates (perfect-sphere geometry, consistent with all other
    grid-doctor output) and all samples per cell are reduced with the
    requested aggregation.

    Parameters
    ----------
    ds:
        Dataset with per-sample latitude/longitude variables (swath
        geolocation, station coordinates, …).  Variables that span the
        sample dimensions are binned; variables that share none of the
        sample dimensions are passed through unchanged; variables that
        overlap them only partially are skipped with a warning.
        Non-sample dimensions (``time``, ``channel``, …) are preserved
        as batch dimensions.
    level:
        Target HEALPix level.  Choose it so the cell spacing
        (``58.6° / 2**level``) is coarser than the sample spacing —
        only then is the per-cell mean a faithful stand-in for
        conservative remapping.
    agg:
        Aggregation per variable: a single method applied to all
        variables or a mapping ``{variable: method}``.  Supported
        methods: ``"mean"`` (continuous fields; binning analogue of
        conservative remapping), ``"mode"`` (categorical fields;
        analogue of nearest-neighbour), ``"min"``, ``"max"``, and
        ``"count"``.  A per-sample *sum* is deliberately not offered:
        it scales with sample density (orbit overlap, across-track
        pixel count) rather than any physical integral.
    nest:
        Use nested HEALPix ordering when *True*.  Nested ordering is
        required for pyramid coarsening.
    lat_name, lon_name:
        Explicit coordinate variable names.  When omitted, the standard
        grid-doctor name lists are searched (``latitude``, ``lat``, …).
    source_units:
        Angular unit convention of the coordinates.
    fill_values:
        Explicit per-variable fill values, e.g. ``{"cloud_type": 255}``.
        When omitted, declared ``_FillValue`` / ``missing_value``
        attributes are honoured; floating-point non-finite values are
        always treated as invalid.  ``0`` is accepted as a fill value.
    min_count:
        Minimum number of valid samples required for a cell to be
        valid.  Cells with fewer samples are set to NaN (does not apply
        to ``"count"``).
    with_counts:
        Add an ``<name>_count`` companion variable per binned variable
        holding the number of valid samples per cell.  Recommended for
        published datasets: it makes coverage auditable and enables
        unbiased merging of overlapping granules downstream.
    dense:
        When *True* (default), return the full ``12 * 4**level`` cell
        array with standard grid-doctor coordinates, CRS variable, and
        attributes — directly consumable by
        [`coarsen_healpix`][grid_doctor.helpers.coarsen_healpix] and
        [`save_pyramid`][grid_doctor.helpers.save_pyramid].  When
        *False*, return a compact dataset containing only the touched
        cells (the ``healpix_index`` coordinate holds the actual HEALPix
        indices) — useful as a per-granule intermediate at high levels;
        convert with
        [`sparse_to_dense`][grid_doctor.swath.sparse_to_dense] before
        coarsening or publishing.

    Returns
    -------
    xarray.Dataset
        Binned dataset on the HEALPix grid.

    Raises
    ------
    ValueError
        On unknown aggregation methods, invalid levels, or when no
        valid sample coordinates exist.

    Examples
    --------
    ```python
    hpx = gd.bin_to_healpix(
        swath,
        level=11,
        agg={"radiance": "mean", "cloud_type": "mode"},
        fill_values={"cloud_type": 255},
        with_counts=True,
    )
    pyramid = {11: hpx}
    for lvl in range(10, -1, -1):
        pyramid[lvl] = gd.coarsen_healpix(pyramid[lvl + 1], lvl)
    ```
    """
    if not 0 <= level <= MAX_NESTED_LEVEL:
        raise ValueError(f"level must be within [0, {MAX_NESTED_LEVEL}].")
    if min_count < 1:
        raise ValueError("min_count must be at least 1.")

    lat, lon, sample_dims = resolve_point_coords(
        ds, lat_name=lat_name, lon_name=lon_name, source_units=source_units
    )
    # Fail-fast: validate every aggregation before any data is loaded.
    methods = resolve_methods(ds, sample_dims, agg)

    valid_coords = np.isfinite(lat) & np.isfinite(lon)
    if not valid_coords.any():
        raise ValueError("No samples with valid (finite) coordinates found.")

    module, kwargs = _require_healpix_geo_module(nest)
    cell_ids = np.asarray(
        module.lonlat_to_healpix(
            lon[valid_coords], lat[valid_coords], depth=level, **kwargs
        ),
        dtype=np.int64,
    )

    # Compact indexing: bin into the touched cells only, scatter later.
    unique_cells, group_idx = np.unique(cell_ids, return_inverse=True)
    group_idx = group_idx.astype(np.int64)
    n_cells = int(unique_cells.size)

    binned: dict[str, xr.DataArray] = {}
    counts: dict[str, xr.DataArray] = {}
    for name, da in ds.data_vars.items():
        var_name = str(name)
        overlap = set(sample_dims) & set(map(str, da.dims))
        if not overlap:
            binned[var_name] = da
            continue
        if overlap != set(sample_dims):
            logger.warning(
                "Skipping %r: covers only part of the sample dimensions %s.",
                var_name,
                sample_dims,
            )
            continue

        method = methods[var_name]

        batch_dims = tuple(d for d in map(str, da.dims) if d not in sample_dims)
        arranged = da.transpose(*batch_dims, *sample_dims)
        fill = (fill_values or {}).get(var_name)
        values = masked_float64(arranged, fill_value=fill)
        values = values.reshape(*arranged.shape[: len(batch_dims)], -1)
        values = values[..., valid_coords]

        valid_count = bin_count(group_idx, values, n_cells=n_cells)

        if method == "count":
            result = valid_count
        elif method == "mode":
            result = bin_mode(group_idx, values, n_cells=n_cells)
            result[valid_count < min_count] = np.nan
        else:
            result = bin_simple(
                group_idx, values, n_cells=n_cells, func=NPG_FUNC[method]
            )
            result[valid_count < min_count] = np.nan

        attrs = {
            key: value for key, value in da.attrs.items() if key not in FILL_ATTR_NAMES
        }
        attrs["grid_doctor_method"] = AGG_TO_METHOD[method]
        binned[var_name] = xr.DataArray(result, dims=(*batch_dims, HEALPIX_INDEX), attrs=attrs)
        if with_counts and method != "count":
            counts[f"{var_name}_count"] = xr.DataArray(
                valid_count.astype(np.int32),
                dims=(*batch_dims, HEALPIX_INDEX),
                attrs={"long_name": f"number of valid samples binned into {var_name}"},
            )

    binned.update(counts)
    result_ds = xr.Dataset(binned, attrs=ds.attrs.copy())

    # Preserve batch coordinates (time, channel, ...).
    keep_coords = {
        str(coord): ds.coords[coord]
        for coord in ds.coords
        if not set(sample_dims) & set(map(str, ds.coords[coord].dims))
    }
    result_ds = result_ds.assign_coords(keep_coords)
    result_ds.attrs["grid_doctor_method"] = _dominant_method(result_ds)

    if dense:
        return _scatter_to_dense(result_ds, unique_cells, level=level, nest=nest)
    return _attach_sparse_coords(result_ds, unique_cells, level=level, nest=nest)


def sparse_to_dense(ds: xr.Dataset) -> xr.Dataset:
    """Scatter a compact (sparse) binned dataset onto the full grid.

    Parameters
    ----------
    ds:
        Output of ``bin_to_healpix(..., dense=False)``.

    Returns
    -------
    xarray.Dataset
        Dense dataset with the standard grid-doctor HEALPix coordinates
        and metadata, ready for
        [`coarsen_healpix`][grid_doctor.helpers.coarsen_healpix].

    Raises
    ------
    ValueError
        When *ds* does not look like a sparse binned dataset.
    """
    if int(ds.attrs.get("grid_doctor_sparse", 0)) != 1:
        raise ValueError("Dataset is not a sparse binned dataset.")
    level = int(ds.attrs[HEALPIX_LEVEL])
    nest = str(ds.attrs.get(HEALPIX_ORDER, HealpixNested)) in {HealpixNested, "nest"}
    cell_ids = np.asarray(ds[HEALPIX_INDEX].values, dtype=np.int64)
    stripped = ds.drop_vars(
        [name for name in ("latitude", "longitude", "crs", HEALPIX_INDEX) if name in ds]
    )
    return _scatter_to_dense(stripped, cell_ids, level=level, nest=nest)


# ===================================================================
# Output assembly
# ===================================================================


def _dominant_method(ds: xr.Dataset) -> str:
    """Return the dataset-level ``grid_doctor_method`` attribute.

    ``"binned-mode"`` wins when *all* binned variables are categorical,
    so that ``coarsen_healpix(..., coarsen_mode="auto")`` selects mode
    coarsening; otherwise ``"binned-mean"`` is used and categorical
    variables should be coarsened separately or with an explicit
    ``coarsen_mode``.
    """
    methods = {
        str(da.attrs.get("grid_doctor_method"))
        for da in ds.data_vars.values()
        if "grid_doctor_method" in da.attrs
    }
    if methods == {"binned-mode"}:
        return "binned-mode"
    return "binned-mean"


def _scatter_to_dense(
    ds: xr.Dataset,
    cell_ids: Int64Array,
    *,
    level: int,
    nest: bool,
) -> xr.Dataset:
    """Scatter compact per-cell arrays onto the full HEALPix grid."""
    npix = 12 * 4**level
    scattered: dict[str, xr.DataArray] = {}
    for name, da in ds.data_vars.items():
        if HEALPIX_INDEX not in da.dims:
            scattered[str(name)] = da
            continue
        arranged = da.transpose(..., HEALPIX_INDEX)
        if np.issubdtype(arranged.dtype, np.integer):
            full = np.zeros((*arranged.shape[:-1], npix), dtype=arranged.dtype)
        else:
            full = np.full((*arranged.shape[:-1], npix), np.nan)
        full[..., cell_ids] = arranged.values
        scattered[str(name)] = xr.DataArray(full, dims=arranged.dims, attrs=da.attrs)
    dense = xr.Dataset(scattered, attrs=ds.attrs.copy())
    dense = dense.assign_coords(
        {
            str(coord): ds.coords[coord]
            for coord in ds.coords
            if HEALPIX_INDEX not in ds.coords[coord].dims and str(coord) != HEALPIX_INDEX
        }
    )
    dense.attrs.pop("grid_doctor_sparse", None)
    method = str(dense.attrs.pop("grid_doctor_method", "binned-mean"))
    return _attach_healpix_coords(dense, level=level, nest=nest, method=method)


def _attach_sparse_coords(
    ds: xr.Dataset,
    cell_ids: Int64Array,
    *,
    level: int,
    nest: bool,
) -> xr.Dataset:
    """Attach coordinates and metadata to a compact binned dataset.

    The ``healpix_index`` coordinate holds the *actual* HEALPix indices of the
    touched cells (unlike the dense representation, where ``healpix_index`` is a
    positional ``arange``).  The dataset is marked with
    ``grid_doctor_sparse = 1``.
    """
    module, kwargs = _require_healpix_geo_module(nest)
    lon_deg, lat_deg = module.healpix_to_lonlat(cell_ids, level, **kwargs)

    from ..remap import _make_crs_variable

    result = ds.assign_coords({
        HEALPIX_INDEX: cell_ids,
        "latitude": (HEALPIX_INDEX, np.asarray(lat_deg, dtype=np.float64)),
        "longitude": (HEALPIX_INDEX, _canonical_lon(np.asarray(lon_deg, dtype=np.float64))),
        "crs": _make_crs_variable(
            level=level, nside=2**level, order=HealpixNested if nest else HealpixRing
        ),
    })
    for name in result.data_vars:
        if HEALPIX_INDEX in result[name].dims:
            result[name].attrs["grid_mapping"] = "crs"

    import grid_doctor as _gd

    result.attrs[HEALPIX_LEVEL] = level
    result.attrs[HEALPIX_NSIDE] = 2**level
    result.attrs[HEALPIX_ORDER] = HealpixNested if nest else HealpixRing
    result.attrs["grid_doctor_version"] = _gd.__version__
    result.attrs["grid_doctor_sparse"] = 1
    return result


__all__ = [
    "bin_to_healpix",
    "sparse_to_dense",
]
