name: Deploy Docs

permissions:
  contents: write
  pages: write
  id-token: write


permissions:
  contents: write


on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "mkdocs.tech.yml"
      - "mkdocs.data.yml"
  pull_request:
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "mkdocs.tech.yml"
      - "mkdocs.data.yml"

  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-name: grid-doctor
          cache-environment: true
          create-args: >-
            python=3.13
            pip
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          init-shell: bash

      - name: Install packages
        shell: bash -l {0}
        run: |
          python -m pip install -e .[dev]
          pip install tox

      - name: Build technical docs
        shell: bash -l {0}
        env:
          SOCIAL_CARDS: "1"
        run: tox -e docs

      - name: Upload technical docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site-tech/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy technical docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
